"""Golden-file regression: stepfind.kv.find_steps vs MATLAB AFindStepsV5.m.

Fixture generated by tests/golden/generate/gen_kv.m on a clean 5-step
synthetic staircase (high SNR, unambiguous step positions).

Important caveat: MATLAB's ``inPenalty`` is a *relative* threshold on the
fractional QE decrease (``P = exp(-inPenalty/len) - 1``), while this
implementation's ``pen_factor`` is an *absolute* threshold (``pen_factor *
var(data) * ln(N)``) -- different penalty parameterizations for the same
algorithm, not numerically interchangeable at face value. This test
therefore doesn't assert pen_factor=2.0 equals MATLAB's ``single(2)``; it
asserts that on unambiguous synthetic data, both implementations recover the
*same* step positions and segment levels, which is the property that
actually matters for correctness.
"""

from __future__ import annotations

import numpy as np

from salafleezers.analysis.stepfind.kv import find_steps

from .conftest import assert_close, load_golden


def test_kv_recovers_same_steps_as_matlab():
    g = load_golden("kv")
    contour = g["contour"]
    expected_positions = g["expected_step_positions"]
    expected_levels = g["expected_levels"]

    result = find_steps(contour, pen_factor=2.0)

    assert result.n_steps == len(expected_positions), (
        f"found {result.n_steps} steps, MATLAB found {len(expected_positions)}"
    )
    np.testing.assert_array_equal(result.step_positions, expected_positions)
    assert_close(result.levels, expected_levels, rtol=1e-3, name="kv levels")
