"""Golden-file regression: filters.window_filter vs MATLAB windowFilter.m.

Fixture generated by tests/golden/generate/gen_filters.m — see that file for
the exact MATLAB call and tests/golden/generate/README.md for how to
regenerate it.

This test caught a real edge-handling divergence: window_filter used to fall
back to scipy's uniform_filter1d(mode='nearest') (edge replication), while
MATLAB's windowFilter(@mean, ...) uses a symmetric shrinking window at the
edges. Fixed in analysis/filters.py::_centered_shrinking_mean — the match is
now exact (to floating-point precision) everywhere, including the edges.
"""

from __future__ import annotations

from salafleezers.analysis.filters import window_filter

from .conftest import assert_close, load_golden

_RTOL = 1e-9


def test_window_filter_half_width_5():
    g = load_golden("filters")
    actual = window_filter(g["x"], fn="mean", half_width=5)
    assert_close(actual, g["expected_hw5"], rtol=_RTOL, name="hw5")


def test_window_filter_half_width_20():
    g = load_golden("filters")
    actual = window_filter(g["x"], fn="mean", half_width=20)
    assert_close(actual, g["expected_hw20"], rtol=_RTOL, name="hw20")
