"""Golden-file regression: wlc.xwlc_extension("basic") vs MATLAB XWLC.m method 1.

Fixture generated by tests/golden/generate/gen_wlc.m.

Only MATLAB method 1 ("Basic theory") is golden-tested: the Python port's
"marko_siggia" and "bouchiat" methods are intentionally *not* literal ports
of MATLAB's method 2 ("legacy"/phage) and method 3 ("wikipedia") -- they use
more standard formulations instead. See COMPARISON.md for details.
"""

from __future__ import annotations

from salafleezers.analysis.wlc import xwlc_extension

from .conftest import assert_close, load_golden


def test_xwlc_basic_method():
    g = load_golden("wlc")
    actual = xwlc_extension(
        g["F"], Lc=1.0,
        P=float(g["P"]), S=float(g["S"]), kT=float(g["kT"]),
        method="basic",
    )
    assert_close(actual, g["expected_x_over_L"], rtol=1e-6, name="xwlc basic")
